# kubectl rollout -n kube-system restart daemonset/cilium deployment/cilium-operator
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: "true"
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    operator:
      replicas: 1
    nodePort:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    gatewayAPI:
      enabled: true
      gatewayClass:
        create: "true"
      hostNetwork:
        enabled: true
    # https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#bind-to-privileged-port
    envoy:
      securityContext:
        capabilities:
          keepCapNetBindService: true
          envoy:
            - NET_BIND_SERVICE
            - NET_ADMIN
            - SYS_ADMIN
    securityContext:
      capabilities:
        ciliumAgent:
             - CHOWN
             - KILL
             - NET_ADMIN
             - NET_RAW
             - IPC_LOCK
             - SYS_MODULE
             - SYS_ADMIN
             - SYS_RESOURCE
             - DAC_OVERRIDE
             - FOWNER
             - SETGID
             - SETUID
             - NET_BIND_SERVICE
