apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dagger-in-argo
  namespace: argo-events
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  entrypoint: dagger-workflow
  volumes:
    - name: dagger-socket
      hostPath:
        path: /var/run/dagger
        type: Directory
    - name: dagger-storage
      emptyDir: {}
  templates:
    - name: dagger-workflow
      sidecars: []
      inputs:
        artifacts:
          - name: project-source
            path: /work
            git:
              repo: "{{workflow.parameters.repo}}"
              revision: "{{workflow.parameters.revision}}"
          - name: dagger-cli
            path: /usr/local/bin
            mode: 0755
            http:
              # replace with the latest available version of Dagger for your platform
              url: https://github.com/dagger/dagger/releases/download/v0.14.0/dagger_v0.14.0_linux_amd64.tar.gz
      container:
        image: alpine:latest
        command: ["sh", "-c"]
        args:
          [
            "dagger {{workflow.parameters.params}}",
          ]
        workingDir: /work
        env:
          - name: "_EXPERIMENTAL_DAGGER_RUNNER_HOST"
            value: "unix:///var/run/dagger/buildkitd.sock"
        volumeMounts:
          - mountPath: /var/run/dagger
            name: dagger-socket
