apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JuanoD/k8s-experiments
    path: ./
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
