apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: elasticsearch
  namespace: logging
spec:
  repo: https://helm.elastic.co
  chart: elasticsearch
  targetNamespace: logging
  createNamespace: true
  version: 8.5.1
  set: {}

  valuesContent: |-
    replicas: 1
    minimumMasterNodes: 1
    secret:
      enabled: true
      password: unsafe_default
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
    volumeClaimTemplate:
      resources:
        requests:
          storage: 5Gi

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kibana
  namespace: logging
spec:
  repo: https://helm.elastic.co
  chart: kibana
  targetNamespace: logging
  createNamespace: true
  version: 8.5.1
  set: {}

  valuesContent: |-
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: my-ca-issuer
      hosts:
        - host: kibana.192-168-1-37.sslip.io
          paths:
           - path: /
      tls:
        - secretName: kibana-tls
          hosts:
            - kibana.192-168-1-37.sslip.io
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: fluentd
  namespace: logging
spec:
  repo: https://fluent.github.io/helm-charts
  chart: fluentd
  targetNamespace: logging
  createNamespace: true
  version: 0.5.2
  set: {}

  valuesContent: |-
    variant: elasticsearch8
    fileConfigs:
      04_outputs.conf: |-
        <label @OUTPUT>
          <match **>
            @id elasticsearch
            @type elasticsearch
            # @log_level debug

            scheme https
            host "elasticsearch-master"
            port 9200
            path ""
            ssl_verify false

            user elastic
            password unsafe_default

            # index_name fluentd
            suppress_type_name true
            logstash_format true
            logstash_prefix "logstash"
            # Don't wait for elastic to start up.
            # verify_es_version_at_startup false
          </match>
        </label>
