---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: monitoring
  namespace: monitoring
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  createNamespace: true
  version: 62.6.0
  set: {}

  valuesContent: |-
    alertmanager:
      ingress:
        enabled: true
        hosts:
          - alertmanager.192-168-1-37.sslip.io
        annotations:
          cert-manager.io/cluster-issuer: my-ca-issuer
        tls:
          - secretName: alertmanager-tls
            hosts:
              - alertmanager.192-168-1-37.sslip.io
    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.192-168-1-37.sslip.io
        annotations:
          cert-manager.io/cluster-issuer: my-ca-issuer
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.192-168-1-37.sslip.io
    prometheus:
      ingress:
        enabled: true
        hosts:
          - prometheus.192-168-1-37.sslip.io
        annotations:
          cert-manager.io/cluster-issuer: my-ca-issuer
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.192-168-1-37.sslip.io
