apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: charts-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  targetNamespace: longhorn-system
  createNamespace: true
  version: 1.6.2
  set: {}

  valuesContent: |-
    defaultSettings:
      replicaSoftAntiAffinity: true
      defaultReplicaCount: 1
    persistence:
      defaultClassReplicaCount: 1
    ingress:
      annotations:
          cert-manager.io/cluster-issuer: my-ca-issuer
      enabled: true
      # host: longhorn.k-1.local
      host: longhorn.192-168-1-37.sslip.io
      tls: true
      tlsSecret: test-tls
      secureBackends: true
