apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagger
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JuanoD/k8s-experiments
    path: manifests/dagger
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
