apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj/argo-events//manifests/cluster-install?ref=v1.9.2&timeout=120
  - ./eventbus.yml
  - ./rbac-wf.yml
  - ./rbac-sensor.yml
  - ./eventsource-webhook.yml
  - ./sensor-webhook.yml
  - ./dagger-template.yml

namespace: argo-events