apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JuanoD/k8s-experiments
    path: workflows/manifests
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
