apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-secrets
  namespace: charts-system
spec:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  targetNamespace: external-secrets
  createNamespace: true
  version: 0.10.4
  set:
    installCRDs: "true"

  # valuesContent: 
