apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ns.yml
  - ./store-config.yml

helmCharts:
  - releaseName: external-secrets
    repo: https://charts.external-secrets.io
    name: external-secrets
    namespace: external-secrets
    version: 0.10.4
    valuesInline:
      installCRDs: true
  - releaseName: vault
    repo: https://helm.releases.hashicorp.com
    name: vault
    namespace: vault
    version: 0.28.1
    valuesInline:
      server:
        dev:
          enabled: true
        ingress:
          enabled: true
          hosts:
            - host: vault.k-1.local
              paths: []
            - host: vault.192-168-1-37.sslip.io
              paths: []
      ui:
        enabled: true
        # serviceType: LoadBalancer
