apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault
  namespace: charts-system
spec:
  repo: https://helm.releases.hashicorp.com
  chart: vault
  targetNamespace: vault
  createNamespace: true
  version: 0.28.1
  set: {}

  valuesContent: |-
    server:
      dev:
        enabled: true
      ingress:
        enabled: true
        hosts:
          - host: vault.k-1.local
            paths: []
          - host: vault.192-168-1-37.sslip.io
            paths: []
    ui:
      enabled: true
      # serviceType: LoadBalancer
