apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ns.yml
  - ./certs.yml

helmCharts:
  - releaseName: cert-manager
    namespace: cert-manager
    repo: https://charts.jetstack.io
    name: cert-manager
    version: 1.15.3
    includeCRDs: true
    valuesInline:
      crds:
        enabled: "true"
      config:
        apiVersion: controller.config.cert-manager.io/v1alpha1
        kind: ControllerConfiguration
        enableGatewayAPI: true
